//! Parity tests for `rust_stats::catch22` against pycatch22
//! (the canonical C implementation).
//!
//! Goldens are generated by `tests/golden/generate.py::catch22_goldens`
//! using `pycatch22.catch22_all(..., catch24=True)`. Each golden carries
//! the input series, pycatch22's feature names, and pycatch22's values.
//! We compute the catch24 panel here and compare per-feature.

use rust_stats::catch22::{catch24, CATCH22_NAMES, CATCH24_EXTRA_NAMES};
use serde::Deserialize;
use std::collections::HashMap;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Golden {
    y: Vec<f64>,
    names: Vec<String>,
    values: Vec<f64>,
}

fn load(name: &str) -> Golden {
    let path: PathBuf = ["tests", "golden", &format!("catch22_{name}.json")]
        .iter()
        .collect();
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!("failed to read {path:?}: {e}; did you run tests/golden/generate.py?")
    });
    serde_json::from_slice(&bytes).expect("invalid golden JSON")
}

fn assert_matches_pycatch22(name: &str, rel_tol: f64, abs_tol: f64) {
    let g = load(name);
    let ref_values: HashMap<&str, f64> = g
        .names
        .iter()
        .map(|s| s.as_str())
        .zip(g.values.iter().copied())
        .collect();

    let ours = catch24(&g.y);
    let our_names: Vec<&str> = CATCH22_NAMES
        .iter()
        .chain(CATCH24_EXTRA_NAMES.iter())
        .copied()
        .collect();

    let mut failures: Vec<String> = Vec::new();
    for (feature_name, ours_v) in our_names.iter().zip(ours.iter().copied()) {
        let ref_v = ref_values
            .get(feature_name)
            .copied()
            .unwrap_or_else(|| panic!("missing reference value for {feature_name} in {name}"));

        let close = (ours_v - ref_v).abs()
            <= abs_tol.max(rel_tol * ours_v.abs().max(ref_v.abs()));
        if !close {
            failures.push(format!(
                "{feature_name}: ours={ours_v}, pycatch22={ref_v}, |Δ|={}",
                (ours_v - ref_v).abs()
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} feature(s) disagree on {name}:\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

#[test]
fn matches_pycatch22_normal_seed0() {
    assert_matches_pycatch22("normal_n200_seed0", 1e-6, 1e-9);
}

#[test]
fn matches_pycatch22_normal_seed1() {
    assert_matches_pycatch22("normal_n200_seed1", 1e-6, 1e-9);
}

#[test]
fn matches_pycatch22_normal_seed7() {
    assert_matches_pycatch22("normal_n200_seed7", 1e-6, 1e-9);
}

#[test]
fn matches_pycatch22_normal_seed42() {
    assert_matches_pycatch22("normal_n200_seed42", 1e-6, 1e-9);
}

#[test]
fn matches_pycatch22_normal_seed1234() {
    assert_matches_pycatch22("normal_n200_seed1234", 1e-6, 1e-9);
}

