//! Parity tests for `rust_stats::tsa::seasonal_decompose` against
//! `statsmodels.tsa.seasonal.seasonal_decompose`. Goldens are generated by
//! `tests/golden/generate.py` (statsmodels 0.14+).
//!
//! Both modes use the same algorithm as statsmodels (centered moving
//! average; phase means; additive subtract / multiplicative divide), so
//! parity is bitwise up to float roundoff.

use approx::assert_relative_eq;
use rust_stats::tsa::{seasonal_decompose, DecomposeMode, SeasonalDecomposeOpts};
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Golden {
    y: Vec<f64>,
    period: u32,
    mode: String,
    trend: Vec<Option<f64>>,
    seasonal: Vec<Option<f64>>,
    residual: Vec<Option<f64>>,
}

fn load(name: &str) -> Golden {
    let path: PathBuf = ["tests", "golden", &format!("seasonal_decompose_{name}.json")]
        .iter()
        .collect();
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!("failed to read {path:?}: {e}; did you run tests/golden/generate.py?")
    });
    serde_json::from_slice(&bytes).expect("invalid golden JSON")
}

fn decompose_mode(name: &str) -> DecomposeMode {
    match name {
        "additive" => DecomposeMode::Additive,
        "multiplicative" => DecomposeMode::Multiplicative,
        other => panic!("unknown mode {other}"),
    }
}

fn assert_dataset(name: &str, max_rel: f64, epsilon: f64) {
    let g = load(name);
    let mut opts = SeasonalDecomposeOpts::new(g.period);
    opts.mode = decompose_mode(&g.mode);
    let d = seasonal_decompose(&g.y, opts).expect("decompose failed");

    let n = g.y.len();
    assert_eq!(d.trend.len(), n);
    assert_eq!(d.seasonal.len(), n);
    assert_eq!(d.residual.len(), n);

    for i in 0..n {
        // Trend NaN edges must coincide.
        match (g.trend[i], d.trend[i].is_nan()) {
            (None, true) => {}
            (Some(ref_), false) => {
                assert_relative_eq!(d.trend[i], ref_, max_relative = max_rel, epsilon = epsilon);
            }
            _ => panic!("trend NaN mismatch at i={i}"),
        }
        if let Some(ref_) = g.seasonal[i] {
            assert_relative_eq!(d.seasonal[i], ref_, max_relative = max_rel, epsilon = epsilon);
        }
        match (g.residual[i], d.residual[i].is_nan()) {
            (None, true) => {}
            (Some(ref_), false) => {
                assert_relative_eq!(d.residual[i], ref_, max_relative = max_rel, epsilon = epsilon);
            }
            _ => panic!("residual NaN mismatch at i={i}"),
        }
    }
}

#[test] fn quarterly_additive()           { assert_dataset("quarterly_additive",          1e-12, 1e-12); }
#[test] fn quarterly_multiplicative()     { assert_dataset("quarterly_multiplicative",    1e-12, 1e-12); }
#[test] fn airpassengers_additive()       { assert_dataset("airpassengers_additive",      1e-12, 1e-12); }
#[test] fn airpassengers_multiplicative() { assert_dataset("airpassengers_multiplicative", 1e-12, 1e-12); }
