"""Generate golden reference values for rust-stats parity tests
(seasonal_decompose, STL, LOESS). OLS goldens are generated by the
sibling crate's script (rust-stats-ols/tests/golden/generate.py).

Run manually:
    python3 tests/golden/generate.py

Pinned versions documented below to make outputs reproducible.
Do NOT run this from cargo test. Outputs are committed to source control.
"""
# Tested with: numpy 2.4+, scipy 1.17+, statsmodels 0.14+, pandas 3.0+

import json
from pathlib import Path

import numpy as np
import statsmodels.datasets as smds
from statsmodels.nonparametric.smoothers_lowess import lowess
from statsmodels.tsa.seasonal import STL, seasonal_decompose

OUT_DIR = Path(__file__).parent


def _quarterly_series(n_years=8, seed=20260510):
    """Quarterly synthetic series: linear trend + sin-driven seasonal + noise."""
    rng = np.random.default_rng(seed)
    n = n_years * 4
    t = np.arange(n, dtype=float)
    trend = 10.0 + 0.25 * t
    seasonal = 3.0 * np.sin(2 * np.pi * t / 4.0) + 1.5 * np.cos(4 * np.pi * t / 4.0)
    noise = rng.standard_normal(n) * 0.5
    return trend + seasonal + noise


def _airpassengers():
    """Classic monthly AirPassengers (1949-01..1960-12, n=144, period=12)."""
    df = smds.get_rdataset("AirPassengers", "datasets").data
    return df["value"].to_numpy().astype(float)


def _ts_fit_decompose(name, y, period, mode):
    res = seasonal_decompose(y, period=period, model=mode, two_sided=True,
                             extrapolate_trend=0)
    out = {
        "y": list(map(float, y)),
        "period": int(period),
        "mode": mode,
        "trend":    [None if np.isnan(v) else float(v) for v in res.trend],
        "seasonal": [None if np.isnan(v) else float(v) for v in res.seasonal],
        "residual": [None if np.isnan(v) else float(v) for v in res.resid],
    }
    target = OUT_DIR / f"seasonal_decompose_{name}.json"
    with target.open("w") as f:
        json.dump(out, f, indent=2)
    print(f"wrote {target}")


def seasonal_decompose_goldens():
    y_q = _quarterly_series()
    _ts_fit_decompose("quarterly_additive",          y_q, 4,  "additive")
    _ts_fit_decompose("quarterly_multiplicative",    y_q + 50.0, 4, "multiplicative")
    y_air = _airpassengers()
    _ts_fit_decompose("airpassengers_additive",      y_air, 12, "additive")
    _ts_fit_decompose("airpassengers_multiplicative", y_air, 12, "multiplicative")


def _stl_fit(name, y, period, seasonal_window, mode):
    if mode == "multiplicative":
        work = np.log(y)
    else:
        work = y
    stl = STL(work, period=period, seasonal=seasonal_window,
              robust=False).fit(inner_iter=2, outer_iter=0)
    if mode == "multiplicative":
        trend, seasonal, resid = np.exp(stl.trend), np.exp(stl.seasonal), np.exp(stl.resid)
    else:
        trend, seasonal, resid = stl.trend, stl.seasonal, stl.resid
    out = {
        "y": list(map(float, y)),
        "period": int(period),
        "seasonal_window": int(seasonal_window),
        "mode": mode,
        "trend":    list(map(float, trend)),
        "seasonal": list(map(float, seasonal)),
        "residual": list(map(float, resid)),
    }
    target = OUT_DIR / f"stl_{name}.json"
    with target.open("w") as f:
        json.dump(out, f, indent=2)
    print(f"wrote {target}")


def stl_goldens():
    y_q = _quarterly_series()
    _stl_fit("quarterly_additive",       y_q,        4,  7, "additive")
    _stl_fit("quarterly_multiplicative", y_q + 50.0, 4,  7, "multiplicative")
    y_air = _airpassengers()
    _stl_fit("airpassengers_additive",       y_air, 12, 7, "additive")
    _stl_fit("airpassengers_multiplicative", y_air, 12, 7, "multiplicative")


def _loess_fit(name, y, span):
    n = len(y)
    x = np.arange(n, dtype=float)
    smoothed = lowess(y, x, frac=span, it=0, return_sorted=False)
    out = {
        "y": list(map(float, y)),
        "span": float(span),
        "degree": 1,
        "smoothed": list(map(float, smoothed)),
    }
    target = OUT_DIR / f"loess_{name}.json"
    with target.open("w") as f:
        json.dump(out, f, indent=2)
    print(f"wrote {target}")


def loess_goldens():
    rng = np.random.default_rng(20260510)
    n = 200
    t = np.linspace(0.0, 4.0 * np.pi, n)
    smooth = np.sin(t) + 0.5 * np.cos(2.0 * t)
    noisy = smooth + rng.standard_normal(n) * 0.3
    _loess_fit("smooth_span30", smooth, 0.30)
    _loess_fit("smooth_span50", smooth, 0.50)
    _loess_fit("noisy_span30",  noisy,  0.30)
    _loess_fit("noisy_span50",  noisy,  0.50)


def main():
    seasonal_decompose_goldens()
    stl_goldens()
    loess_goldens()


if __name__ == "__main__":
    main()
